[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hotwing_contract = "L1dCurNdHKSmpRHFKGcaNf64qzExvCMGuZbU3uun6ow"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
