[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.26" # Solana version to use

[test]
upgradeable = true

[features]
resolution = true
skip-lint = false

[programs.devnet]
hotwing_contract = "L1dCurNdHKSmpRHFKGcaNf64qzExvCMGuZbU3uun6ow"

[registry]
url = "https://api.apr.dev"

[clusters]
devnet = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/hotRUj9Bso8Et2hUmnzBndWvwAVJ1s8fLnSaAGQHNg5.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
