[package]
name = "hotwing-contract"  # Replace this with your program name
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []          # Standard feature to disable entrypoint generation
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.30.1"     # Anchor framework core library
anchor-spl = "0.30.1"      # Anchor framework SPL (Solana Program Library) integration
pyth-sdk-solana = "0.10.2" # Replace with the latest version (check the Pyth SDK docs)